### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by acxz** [ddmarshall/Code-Eli#59]
Are there any plans to make this library installable? i.e `sudo make install` and `sudo make uninstall` targets? This would make it easier for other projects that depend on/want to use this library so that it is much easier to link to.

**Comment by acxz** [comment]
@ramcdona Since this repo is not being maintained, would it be possible to allow us to submit issues on your fork of code-eli? Something like this: https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

**Comment by ramcdona** [comment]
Done.

Code-Eli is header-only, so there is no such thing as linking to it.  It won't ever need to be installed on a machine as a shared library.

That said, I can certainly understand some benefit to expanding the CMake setup to allow for a better 'make install' target (so long as it doesn't break the way things currently work).  So I would be happy to integrate such a change into my fork.

What project are you looking to use Code-Eli in?

There are a handful of things I have done in OpenVSP that probably should have been done in Code-Eli -- but it was expeditious to do it that way.  Since there were no other users, the penalty was not great.  If those features end up looking attractive to you, we may want to chart a path to migrate those things into Code-Eli.

**Comment by acxz** [comment]
Thanks for the quick response! Haha yeah im looking at packaging OpenVSP for a couple of Linux platforms namely ArchLinux (creating an AUR package) and Ubuntu (creating a PPA package). I was going to post an issue on OpenVSP for creating a PPA package after I got it to work on my system first with all the dependencies.

But yeah my end goal for packaging code-eli is for openvsp, it's just that I like for things to be modularized. So that when I create a package I can say openvsp depends on the code-eli package, even if no one else uses code-eli besides openvsp.

**Comment by acxz** [comment]
I'll go ahead and close this issue and open up a related one on your fork.
